### ISSUE TITLE
I encountered a connection error on 1.19 forge. Restore after deleting it.

### ISSUE THREAD

**Issue by xlive2233** [GeheimagentNr1/EasierSleeping#3]
I encountered a connection error on 1.19 forge. Restore after deleting it.
![Screenshot_2022-06-17-01-02-34-416_cn lingwoyun cpc](https://user-images.githubusercontent.com/28977537/174128955-7b321db4-5e3f-4501-af4b-3e0b90af2c0d.jpg)

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Further information requested</td></tr><tr><th>Issue type:</th><td>Bug</td></tr><tr><th>Fix type:</th><td>tba</td></tr><tr><th>Fix version:</th><td>tba</td></tr><tr><th>Fix release date:</th><td>tba</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**

*   [x] Try to reproduce issue, with Forge 41.0.38, Minecraft 1.19, Mod version 2.1.0  
    Issue cannot be reproduced.

**Comment by GeheimagentNr1** [comment]
Which Forge version are you using?  
What other mods are installed or which modpack are you using?

**Comment by DatBoiOmonie** [comment]
got the error too, seems to be conflicting with fantasy furniture

**Comment by DatBoiOmonie** [comment]
my exact error is his, but heres some relevant error:
Radium Class Analysis Error: Class xyz.apex.forge.fantasyfurniture.common.block.furniture.BedSingleBlock cannot be analysed, because getting declared methods crashes with RuntimeException: Attempted to load class com/mojang/blaze3d/vertex/PoseStack for invalid dist DEDICATED_SERVER. This is usually caused by modded entities declaring methods that have a return type or parameter type that is annotated with @OnlyIn(Dist.CLIENT).

**Comment by DatBoiOmonie** [comment]
im pretty active, so if u want to fix this and have any kinda questions please feel free to ask

**Comment by DatBoiOmonie** [comment]
> Which Forge version are you using? What other mods are installed or which modpack are you using?

please reopen the case
